name: build
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - run: brew install ldid || true
      - run: bash build.sh
      - uses: actions/upload-artifact@v4
        with:
          name: AdCleaner.dylib
          path: build/AdCleaner.dylib
